project:
  type: website
  output-dir: docs

# Meta
description-meta: "Tomás Urzúa – Sociologist - Social Sciences Master's Student"
author-meta: "Tomás Urzúa"

website:
  title: "Tomás Urzúa's Website"
  image: "/files/tomas.jpg"
  description: "Tomás Urzúa – Social Sciences Master's Student"

  navbar:
    background: dark

    left:
    #  - text: Home
    #    href: index.qmd
    #  - text: About
    #    menu:
    #      - text: News
    #        href: posts.qmd#category=news
    #      - text: Events
    #        href: posts.qmd#category=event   
     - text: Research
       menu:
          - text: Projects
            href: projects.qmd
          - text: Publications
            href: publications.qmd
          - text: Presentations
            href: presentations.qmd  
            target: _blank 
     - text: Teaching
       href: teaching.qmd

    right: 
      - text: "**CV**"
        href: files/cv-1.pdf
        target: _blank 
      - icon: github
        href: https://github.com/tomasurzuam
        target: _blank
  
  page-navigation: true
  
  page-footer: 
    center: "[Tomás Urzúa](https://renejcanales.github.io) &copy; <script>document.write(new Date().getFullYear())</script>"
    # left: "[Tomás Urzúa](https://renejcanales.github.io); <script>document.write(new Date().getFullYear())</script>" 
    right:  
       - icon: github
         href: https://github.com/tomasurzuam
         target: _blank
    #   - text: "{{< fa brands bluesky >}}" 
    #     href: https://bsky.app/profile/hegang.bsky.social
    #     target: _blank
    #   - icon: rss
    #     href: posts.xml
    #     target: _blank  
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: false

  draft-mode: unlinked
  
  repo-url: https://github.com/renejcanales/renejcanales.github.io
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://renejcanales.github.io"


bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"

