---
title: "Publications"
description-meta: "Information, PDFs, and social metrics of papers"
#page-layout: full
#back-to-top-navigation: true
title-block-banner: false
css: /custom.css
---
::: {.justify}

<!--This is my personal clarity, please delete or replace with your own clarity-->
{{< include /files/includes/_msclarity.qmd >}}

<!--Include academic icons or buttons-->
{{< include /files/includes/_academic.qmd >}}

## Peer-reviewed Articles


Castillo, J. C., Canales Sellés, R., Laffert, A., & Urzúa, T. (2026). Justification trajectories for pension inequality in Chile (2016–2023): the role of social class and beliefs in meritocracy. [Frontiers in Sociology, 11, 1771856](https://doi.org/10.3389/fsoc.2026.1771856). 


Karle, C., Sánchez-Barría, F., & Canales Sellés, R. (2026). When Protest Becomes Institutionalized: Evidence from the Chilean Student Movement Under Military Rule, 1982–1989. [The Sociological Quarterly, 1–27](https://doi.org/10.1080/00380253.2026.2643335)

## In Preparation

**Stability and comparability of meritocratic beliefs in school-age students: A measurement invariance approach across time and cohorts**. Andreas Laffert, Juan Carlos Castillo, René Canales, Tomás Urzúa & Kevin Carrasco. *Submited*. [Preprint](https://doi.org/10.31235/osf.io/gvbqw_v1)

**Attitudes towards political violence in the chilean contentious cycle: A longitudinal analysis from education and participation**. René Canales & Daniel Miranda. *In progress*.

**Youth, Authoritarian Heritage and Democracy: A Multilevel Analysis of the disposition to Institutional Participation in Europe**. René Canales, Ricardo León & Daniel Miranda. *In progress*.

## Research Reports and Data Visualizations

Urzúa, T., Canales, R., Laffert, A. & Castillo, J. C. (2025). [Documento Metodológico VisELSOC (Release)](https://ocscoes.github.io/propuesta-medicion-elsoc/output/book-cohesion-elsoc/docs/). ocs-coes. Zenodo. https://doi.org/10.5281/zenodo.17418461

Urzúa, T., Iturra, J., Canales, R., Laffert, A. & Castillo, J.C. (2025). [Visualizador Longitudinal de Cohesión Social en Chile (Release)](https://ocs-coes.shinyapps.io/ocs-viselsoc/). Zenodo. https://doi.org/10.5281/zenodo.17408346

## Press Articles

Canales, R. & Castillo, J.C. (2025). *La seguridad nace del vínculo social*. [Tercera Dosis](https://terceradosis.cl/2025/10/10/la-seguridad-nace-del-vinculo-social/)

:::
